#import "Foundation/Foundation.h"
#import "U8ProductInfo.h"

typedef void(^completedHandler)(NSData *data, NSURLResponse *response, NSError *error);

// HttpUtil is a singleton class used to request remote server.
@interface HttpUtil:NSObject {
    NSString *_apiBaseURL;
}
+ (instancetype)sharedInstance; 
- (void)setBaseURL:(NSString *)url;
- (NSURLSessionDataTask *)collectInGameProductData:(NSString *)prodID 
    bundleID:(NSString *)bundleID
    prodName:(NSString *)prodName 
    prodDesc:(NSString *)prodDesc
    price:(NSNumber *) price
    quantity:(long long)quantity
    completedHandler:(completedHandler)completedHandler;
- (void)vendorBuyInGameProductData;
- (void)exportItemToCustomerFromStoreHouse;

// "retain" is needed when the attribute is a pointer to an object. The setter generated by @synthesize will retain (aka add a retain count) the object. You will need to release the object when you are finished with it. "copy" is needed when the object is mutable.Oct 22, 2011
@property(retain, nonatomic) NSString *apiBaseURL; // @synthesize apiBaseURL=_apiBaseURL

@end