//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@protocol AVPPlayerTextureDelegate <NSObject>
- (NSDictionary *)pixelBufferAttributes:(_Bool)arg1;
- (void)renderPlayerTexture:(id <AVPPlayerTexture>)arg1;
- (void)updatePlayerTexture:(id <AVPPlayerTexture>)arg1 fromPixelBuffer:(struct __CVBuffer *)arg2;
- (void)freePlayerTexture:(id <AVPPlayerTexture>)arg1;
- (id <AVPPlayerTexture>)createPlayerTexture;
- (void)createPlatformResources;
@end

