//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVPPlayerTexture.h"

@class NSString;

@interface AVPPlayerOpenGLESTexture : NSObject <AVPPlayerTexture>
{
    CDStruct_53a76075 _textures[2];
    unsigned long long _numTextures;
    _Bool _sizeHasChanged;
    id <AVPPlayerTextureDelegate> _delegate;
    struct __CVOpenGLESTextureCache *_textureCache;
}

@property(readonly, nonatomic) _Bool sizeHasChanged; // @synthesize sizeHasChanged=_sizeHasChanged;
@property(readonly, nonatomic) struct __CVOpenGLESTextureCache *textureCache; // @synthesize textureCache=_textureCache;
@property(readonly, nonatomic) unsigned long long cvTexturesCount; // @synthesize cvTexturesCount=_numTextures;
@property(readonly, nonatomic) __weak id <AVPPlayerTextureDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setTextures:(CDStruct_53a76075 *)arg1 count:(unsigned long long)arg2;
- (_Bool)getTextures:(CDStruct_8eb9edb3 *)arg1 count:(int *)arg2;
- (void)dealloc;
- (id)initWithTextureDelegate:(id)arg1 textureCache:(struct __CVOpenGLESTextureCache *)arg2;
- (id)initWithDelegate:(id)arg1;
@property(readonly, nonatomic) CDStruct_53a76075 *cvTextures;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

