//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPPlayer, AVPPlayerAudioCaptureBuffer;

@interface AVPPlayerAudioProcessingTapStorage : NSObject
{
    _Bool _isProcessing;
    _Bool _requiresResampling;
    unsigned int _resamplerInputBufferSize;
    AVPPlayer *_player;
    struct OpaqueAudioConverter *_interleaver;
    AVPPlayerAudioCaptureBuffer *_interleaverBuffer;
    struct OpaqueAudioConverter *_resampler;
    struct AudioStreamBasicDescription _processingFormat;
    struct AudioStreamBasicDescription _interleaverFormat;
    struct AudioStreamBasicDescription _resamplerFormat;
}

@property(nonatomic) _Bool requiresResampling; // @synthesize requiresResampling=_requiresResampling;
@property(nonatomic) unsigned int resamplerInputBufferSize; // @synthesize resamplerInputBufferSize=_resamplerInputBufferSize;
@property(nonatomic) struct OpaqueAudioConverter *resampler; // @synthesize resampler=_resampler;
@property(nonatomic) struct AudioStreamBasicDescription resamplerFormat; // @synthesize resamplerFormat=_resamplerFormat;
@property(retain, nonatomic) AVPPlayerAudioCaptureBuffer *interleaverBuffer; // @synthesize interleaverBuffer=_interleaverBuffer;
@property(nonatomic) struct OpaqueAudioConverter *interleaver; // @synthesize interleaver=_interleaver;
@property(nonatomic) struct AudioStreamBasicDescription interleaverFormat; // @synthesize interleaverFormat=_interleaverFormat;
@property(nonatomic) struct AudioStreamBasicDescription processingFormat; // @synthesize processingFormat=_processingFormat;
@property(nonatomic) _Bool isProcessing; // @synthesize isProcessing=_isProcessing;
@property(retain, nonatomic) AVPPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;

@end

