//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVPPlayerTextureDelegate.h"

@class NSString;

@interface AVPPlayerMetalTextureDelegate : NSObject <AVPPlayerTextureDelegate>
{
}

- (id)pixelBufferAttributes:(_Bool)arg1;
- (void)renderPlayerTexture:(id)arg1;
- (void)updatePlayerTexture:(id)arg1 fromPixelBuffer:(struct __CVBuffer *)arg2;
- (void)freePlayerTexture:(id)arg1;
- (id)createPlayerTexture;
- (void)createPlatformResources;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

