//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVPPlayerOpenGLESTextureDelegateBase.h"

@interface AVPPlayerOpenGLES20TextureDelegate : AVPPlayerOpenGLESTextureDelegateBase
{
}

- (unsigned int)formatForPixelBuffer:(struct __CVBuffer *)arg1 plane:(int)arg2;
- (int)internalFormatForPixelBuffer:(struct __CVBuffer *)arg1 plane:(int)arg2;

@end

