//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface AVPPlayerAudioCaptureBuffer : NSObject
{
    NSMutableData *_data;
    char *_bytes;
    unsigned long long _capacity;
    // Error parsing type: AQ, name: _read
    // Error parsing type: AQ, name: _write
    // Error parsing type: AQ, name: _watermark
}

- (void).cxx_destruct;
- (unsigned long long)advanceBy:(unsigned long long)arg1;
- (void)commitBytes:(unsigned long long)arg1;
- (void *)reserveBytes:(unsigned long long)arg1;
- (unsigned long long)getBytes:(void *)arg1 length:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long length;
@property(readonly, nonatomic) unsigned long long contiguousLength;
@property(readonly, nonatomic) const void *contiguousBytes;
- (id)initWithCapacity:(unsigned long long)arg1;

@end

