//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol AVPPlayerTexture <NSObject>
@property(readonly, nonatomic) __weak id <AVPPlayerTextureDelegate> delegate;
- (_Bool)getTextures:(CDStruct_8eb9edb3 *)arg1 count:(int *)arg2;
- (id)initWithDelegate:(id <AVPPlayerTextureDelegate>)arg1;
@end

