//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVPPlayerTexture.h"

@class NSLock, NSString;

@interface AVPPlayerMetalTexture : NSObject <AVPPlayerTexture>
{
    NSLock *_lock;
    struct {
        struct __CVBuffer *_cvTextures[2];
        int _cvTexturesCount;
    } _buffers[2];
    int _crntBuffer;
    id <AVPPlayerTextureDelegate> _delegate;
    struct __CVMetalTextureCache *_textureCache;
}

@property(readonly, nonatomic) struct __CVMetalTextureCache *textureCache; // @synthesize textureCache=_textureCache;
@property(readonly, nonatomic) __weak id <AVPPlayerTextureDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setCvTextures:(struct __CVBuffer **)arg1 count:(unsigned long long)arg2;
- (void)copyCvTextures:(struct __CVBuffer **)arg1 count:(unsigned long long *)arg2;
- (_Bool)getTextures:(CDStruct_8eb9edb3 *)arg1 count:(int *)arg2;
- (void)dealloc;
- (id)initWithTextureDelegate:(id)arg1 textureCache:(struct __CVMetalTextureCache *)arg2;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

