//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAssetResourceLoaderDelegate.h"

@class AVAsset, AVMediaSelectionGroup, AVPPlayerAudioCaptureBuffer, AVPlayer, AVPlayerItem, NSArray, NSData, NSLock, NSMutableDictionary, NSNumber, NSString, NSURL;

@interface AVPPlayer : NSObject <AVAssetResourceLoaderDelegate>
{
    int _lastError;
    int _audioCaptureChannelCount;
    _Bool _useYpCbCr;
    _Bool _hasAudio;
    _Bool _hasVideo;
    _Bool _hasMetaData;
    _Bool _playWithoutBuffering;
    _Bool _looping;
    _Bool _muted;
    _Bool _textureSizeChanged;
    _Bool _resumePlaybackOnAudioSessionRouteChange;
    _Bool _playWhenReady;
    _Bool _isHap;
    _Bool _audioPausedDueToAudioSessionRouteChange;
    _Bool _audioCaptureEnabled;
    int _status;
    float _nominalFrameRate;
    int _frameCount;
    float _rate;
    float _volume;
    int _numFrameSamples;
    int _audioCaptureSampleRate;
    id <AVPPlayerTexture> _texture;
    NSNumber *_handle;
    double _currentTime;
    double _currentDate;
    double _duration;
    double _frameRate;
    NSURL *_keyServerURL;
    NSString *_keyServerAuthToken;
    NSData *_decryptionKey;
    id <AVPPlayerTextureDelegate> _textureDelegate;
    AVAsset *_asset;
    AVPlayer *_player;
    AVPlayerItem *_playerItem;
    id <AVPPlayerItemVideoOutput> _playerItemVideoOutput;
    double _lastFrameTime;
    AVMediaSelectionGroup *_audioSelectionGroup;
    AVMediaSelectionGroup *_visualSelectionGroup;
    NSMutableDictionary *_valueDidChangeObservers;
    long long _YpCbCrMatrix;
    AVPPlayerAudioCaptureBuffer *_audioCaptureBuffer;
    NSLock *_audioCaptureBufferLock;
    struct CGSize _naturalSize;
    struct CGAffineTransform _transform;
}

+ (void)initialize;
@property(retain, nonatomic) NSLock *audioCaptureBufferLock; // @synthesize audioCaptureBufferLock=_audioCaptureBufferLock;
@property(retain, nonatomic) AVPPlayerAudioCaptureBuffer *audioCaptureBuffer; // @synthesize audioCaptureBuffer=_audioCaptureBuffer;
@property(nonatomic) int audioCaptureSampleRate; // @synthesize audioCaptureSampleRate=_audioCaptureSampleRate;
@property(nonatomic) _Bool audioCaptureEnabled; // @synthesize audioCaptureEnabled=_audioCaptureEnabled;
@property(nonatomic) _Bool audioPausedDueToAudioSessionRouteChange; // @synthesize audioPausedDueToAudioSessionRouteChange=_audioPausedDueToAudioSessionRouteChange;
@property(nonatomic) long long YpCbCrMatrix; // @synthesize YpCbCrMatrix=_YpCbCrMatrix;
@property(retain, nonatomic) NSMutableDictionary *valueDidChangeObservers; // @synthesize valueDidChangeObservers=_valueDidChangeObservers;
@property(retain, nonatomic) AVMediaSelectionGroup *visualSelectionGroup; // @synthesize visualSelectionGroup=_visualSelectionGroup;
@property(retain, nonatomic) AVMediaSelectionGroup *audioSelectionGroup; // @synthesize audioSelectionGroup=_audioSelectionGroup;
@property(nonatomic) _Bool isHap; // @synthesize isHap=_isHap;
@property(nonatomic) _Bool playWhenReady; // @synthesize playWhenReady=_playWhenReady;
@property(nonatomic) double lastFrameTime; // @synthesize lastFrameTime=_lastFrameTime;
@property(nonatomic) int numFrameSamples; // @synthesize numFrameSamples=_numFrameSamples;
@property(retain, nonatomic) id <AVPPlayerItemVideoOutput> playerItemVideoOutput; // @synthesize playerItemVideoOutput=_playerItemVideoOutput;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
@property(nonatomic) __weak id <AVPPlayerTextureDelegate> textureDelegate; // @synthesize textureDelegate=_textureDelegate;
@property(retain, nonatomic) NSData *decryptionKey; // @synthesize decryptionKey=_decryptionKey;
@property(retain, nonatomic) NSString *keyServerAuthToken; // @synthesize keyServerAuthToken=_keyServerAuthToken;
@property(retain, nonatomic) NSURL *keyServerURL; // @synthesize keyServerURL=_keyServerURL;
@property(nonatomic) _Bool resumePlaybackOnAudioSessionRouteChange; // @synthesize resumePlaybackOnAudioSessionRouteChange=_resumePlaybackOnAudioSessionRouteChange;
@property(nonatomic, getter=isTextureSizeChanged) _Bool textureSizeChanged; // @synthesize textureSizeChanged=_textureSizeChanged;
@property(nonatomic, getter=isMuted) _Bool muted; // @synthesize muted=_muted;
@property(nonatomic, getter=isLooping) _Bool looping; // @synthesize looping=_looping;
@property(nonatomic) float volume; // @synthesize volume=_volume;
@property(nonatomic) float rate; // @synthesize rate=_rate;
@property(nonatomic) _Bool playWithoutBuffering; // @synthesize playWithoutBuffering=_playWithoutBuffering;
@property(nonatomic) _Bool hasMetaData; // @synthesize hasMetaData=_hasMetaData;
@property(readonly, nonatomic) _Bool hasVideo; // @synthesize hasVideo=_hasVideo;
@property(readonly, nonatomic) _Bool hasAudio; // @synthesize hasAudio=_hasAudio;
@property(readonly, nonatomic) double frameRate; // @synthesize frameRate=_frameRate;
@property(readonly, nonatomic) int frameCount; // @synthesize frameCount=_frameCount;
@property(readonly, nonatomic) struct CGAffineTransform transform; // @synthesize transform=_transform;
@property(readonly, nonatomic) float nominalFrameRate; // @synthesize nominalFrameRate=_nominalFrameRate;
@property(readonly, nonatomic) struct CGSize naturalSize; // @synthesize naturalSize=_naturalSize;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) double currentDate; // @synthesize currentDate=_currentDate;
@property(readonly, nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
@property(readonly, nonatomic) _Bool useYpCbCr; // @synthesize useYpCbCr=_useYpCbCr;
@property(readonly, nonatomic) NSNumber *handle; // @synthesize handle=_handle;
@property(retain, nonatomic) id <AVPPlayerTexture> texture; // @synthesize texture=_texture;
@property(nonatomic) int status; // @synthesize status=_status;
- (void).cxx_destruct;
- (_Bool)getYpCbCrTransform:(float *)arg1;
- (void)addValueDidChangeObserver:(id)arg1 forKeyPath:(id)arg2 flags:(long long)arg3;
- (id)displayNameForVideoTrack:(unsigned long long)arg1;
- (id)displayNameForAudioTrack:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long selectedVideoTrackBitrate;
@property(readonly, nonatomic) NSString *selectedVideoTrackDisplayName;
@property(nonatomic) unsigned long long selectedVideoTrack;
@property(readonly, nonatomic) unsigned long long videoTrackCount;
@property(readonly, nonatomic) unsigned long long selectedAudioTrackBitrate;
@property(readonly, nonatomic) NSString *selectedAudioTrackDisplayName;
@property(nonatomic) unsigned long long selectedAudioTrack;
@property(readonly, nonatomic) unsigned long long audioTrackCount;
- (void)playerItemPlaybackStalledNotification:(id)arg1;
- (void)playerItemDidPlayToEndTimeNotification:(id)arg1;
- (void)prepareAssetForPlayback:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofPlayerItem:(id)arg2 change:(id)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofPlayer:(id)arg2 change:(id)arg3;
- (int)extractFrameTextures:(CDStruct_8eb9edb3 *)arg1 count:(int *)arg2 timeout:(double)arg3;
- (void)render;
- (_Bool)update;
- (void)seekToTime:(double)arg1 toleranceBefore:(double)arg2 toleranceAfter:(double)arg3;
- (void)seekToTime:(double)arg1;
- (void)seekFastToTime:(double)arg1;
- (void)pause;
- (void)play;
- (void)startPlayer;
- (void)close;
- (void)freePlayerItem;
- (_Bool)openURL:(id)arg1 headers:(id)arg2;
- (_Bool)openURL:(id)arg1;
- (_Bool)openFile:(id)arg1;
- (void)setLastError:(int)arg1;
@property(readonly, nonatomic) int lastError;
@property(readonly, nonatomic) NSArray *seekableTimeRanges;
@property(readonly, nonatomic) NSArray *loadedTimeRanges;
@property(readonly, nonatomic) double bufferingProgress;
- (void)shutdown;
- (void)dealloc;
- (id)initWithHandle:(id)arg1 useYpCbCr:(_Bool)arg2;
- (void)audioSessionRouteChangeNotification:(id)arg1;
- (void)addAudioProcessingTapToTrack:(id)arg1;
- (void)copyAudioToBuffer:(float *)arg1 length:(int)arg2;
- (void)enableAudioCaptureWithSampleRate:(int)arg1 channelCount:(int)arg2;
@property(nonatomic) int audioCaptureChannelCount;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

