//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIDevice;

@interface Hardware : NSObject
{
    UIDevice *dev;
}

- (void).cxx_destruct;
- (id)mac;
- (id)batteryLevel;
- (id)UUID;
- (id)phoneMetrics;
- (id)phoneVersion;
- (id)phoneName;
- (id)model;
- (id)detail;
- (id)init;

@end

