//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HGBaseTools : NSObject
{
}

+ (id)getLocalSavedGUID;
+ (id)getKeychainSavedGUID:(id)arg1;
+ (id)getDeviceGUID:(id)arg1;
+ (void)saveDeviceGUID:(id)arg1 guid:(id)arg2;

@end

