//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface P31 : NSObject
{
}

+ (id)unityViewController;
+ (void)unityPause:(_Bool)arg1;
+ (const char *)jsonFromError:(id)arg1;
+ (id)jsonStringFromError:(id)arg1;
+ (id)objectFromJsonString:(id)arg1;
+ (id)jsonStringFromObject:(id)arg1;
+ (_Bool)isValidJsonObject:(id)arg1;

@end

