//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface PVRTexture : NSObject
{
    NSData *_data;
    const struct pvr_header *_header;
    const struct pvr_meta_header *_meta_header;
    const char *_texture_data;
}

@property(nonatomic) const char *texture_data; // @synthesize texture_data=_texture_data;
@property(nonatomic) const struct pvr_meta_header *meta_header; // @synthesize meta_header=_meta_header;
@property(nonatomic) const struct pvr_header *header; // @synthesize header=_header;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (unsigned long long)bytesPerRow:(unsigned long long)arg1;
- (_Bool)getGlInternalFormat:(unsigned int *)arg1 format:(unsigned int *)arg2 type:(unsigned int *)arg3 linear:(_Bool)arg4;
- (unsigned int)glTextureLinear:(_Bool)arg1;
- (unsigned int)glTexture;
@property(readonly, nonatomic) unsigned long long mipMapCount;
@property(readonly, nonatomic) unsigned long long height;
@property(readonly, nonatomic) unsigned long long width;
- (id)initWithData:(id)arg1;
- (unsigned long long)metalPixelFormat:(_Bool)arg1;
- (id)metalTextureWithDevice:(id)arg1 linear:(_Bool)arg2;
- (id)metalTextureWithDevice:(id)arg1;

@end

