//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RandomUUID : NSObject
{
    unsigned char isnew;
    NSString *uuid;
}

- (void).cxx_destruct;
- (id)getuuid;
- (id)getprefix;
- (id)newuuid;
- (id)detail;
- (id)readuuid;
- (id)init;

@end

