//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface SelfApp : NSObject
{
    NSDictionary *infoDic;
}

- (void).cxx_destruct;
- (id)creationTime;
- (id)sdkName;
- (id)identifier;
- (id)version;
- (id)appName;
- (id)detail;
- (id)init;

@end

