//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface SKPluginTransaction : NSObject <NSCoding>
{
    NSString *_productIdentifier;
    NSString *_transactionIdentifier;
    NSString *_applicationUsername;
    unsigned long long _quantity;
    unsigned long long _totalDownloads;
}

+ (void)saveTransaction:(id)arg1;
+ (id)savedTransactions;
+ (id)documentsPathForFile:(id)arg1;
@property(nonatomic) unsigned long long totalDownloads; // @synthesize totalDownloads=_totalDownloads;
@property(nonatomic) unsigned long long quantity; // @synthesize quantity=_quantity;
@property(retain, nonatomic) NSString *applicationUsername; // @synthesize applicationUsername=_applicationUsername;
@property(retain, nonatomic) NSString *transactionIdentifier; // @synthesize transactionIdentifier=_transactionIdentifier;
@property(retain, nonatomic) NSString *productIdentifier; // @synthesize productIdentifier=_productIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

