//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSError, NSString, StoreKitReceiptRequest;

@protocol StoreKitReceiptRequestDelegate
- (void)storeKitReceiptRequest:(StoreKitReceiptRequest *)arg1 validatedWithStatusCode:(int)arg2;
- (void)storeKitReceiptRequest:(StoreKitReceiptRequest *)arg1 validatedWithResponse:(NSString *)arg2;
- (void)storeKitReceiptRequest:(StoreKitReceiptRequest *)arg1 didFailWithError:(NSError *)arg2;
@end

