//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData, NSString;

@interface StoreKitReceiptRequest : NSObject
{
    id <StoreKitReceiptRequestDelegate> _delegate;
    _Bool _isTest;
    NSString *_secret;
    NSMutableData *_responseData;
}

@property(retain, nonatomic) NSString *secret; // @synthesize secret=_secret;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)validateReceipt:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 secret:(id)arg2 isTest:(_Bool)arg3;
- (id)initWithDelegate:(id)arg1 isTest:(_Bool)arg2;

@end

