//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

@interface U8AlertView : UIAlertView
{
}

- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showWithBlock:(CDUnknownBlockType)arg1;

@end

