//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, U8ProductInfo;

@protocol U8Pay
- (void)pay:(U8ProductInfo *)arg1;

@optional
- (void)finishTransactionId:(NSString *)arg1;
- (void)closeIAP;
- (void)openIAP;
@end

