//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSData, NSDictionary, NSError, NSString, NSURL, NSUserActivity, U8UserExtraData, UIApplication, UILocalNotification;

@protocol U8PluginProtocol
- (id)initWithParams:(NSDictionary *)arg1;

@optional
- (void)didReceiveRemoteNotification:(NSDictionary *)arg1;
- (void)didReceiveLocalNotification:(UILocalNotification *)arg1;
- (void)didFailToRegisterForRemoteNotificationsWithError:(NSError *)arg1;
- (void)didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)arg1;
- (void)applicationWillTerminate:(UIApplication *)arg1;
- (void)applicationDidBecomeActive:(UIApplication *)arg1;
- (void)applicationWillEnterForeground:(UIApplication *)arg1;
- (void)applicationDidEnterBackground:(UIApplication *)arg1;
- (void)applicationWillResignActive:(UIApplication *)arg1;
- (void)application:(UIApplication *)arg1 didFinishLaunchingWithOptions:(NSDictionary *)arg2;
- (_Bool)application:(UIApplication *)arg1 continueUserActivity:(NSUserActivity *)arg2 restorationHandler:(void (^)(NSArray *))arg3;
- (_Bool)application:(UIApplication *)arg1 openURL:(NSURL *)arg2 options:(NSDictionary *)arg3;
- (_Bool)application:(UIApplication *)arg1 handleOpenURL:(NSURL *)arg2;
- (_Bool)application:(UIApplication *)arg1 openURL:(NSURL *)arg2 sourceApplication:(NSString *)arg3 annotation:(id)arg4;
- (void)submitExtraData:(U8UserExtraData *)arg1;
- (void)setupWithParams:(NSDictionary *)arg1;
- (_Bool)isInitCompleted;
@end

