//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "U8PluginProtocol.h"

@class NSDictionary, NSMutableArray;

@interface U8Plugin : NSObject <U8PluginProtocol>
{
    NSMutableArray *interfaces;
    NSDictionary *_params;
}

@property(copy, nonatomic) NSDictionary *params; // @synthesize params=_params;
- (void).cxx_destruct;
- (void)eventSDKInternalError:(id)arg1;
- (void)eventCustom:(id)arg1 params:(id)arg2;
- (void)eventPayFailed:(id)arg1;
- (void)eventPayPaid:(id)arg1;
- (void)eventUserSwitchAccount;
- (void)eventUserLogout:(id)arg1;
- (void)eventUserLoginAll:(id)arg1;
- (void)eventUserLoginExt:(id)arg1;
- (void)eventUserLoginFailed;
- (void)eventUserLogin:(id)arg1;
- (void)eventPlatformInitFailed;
- (void)eventPlatformInit:(id)arg1;
- (void)registerInterface:(id)arg1;
- (id)getInterface:(id)arg1;
- (id)viewController;
- (id)view;
- (_Bool)getBoolForParam:(id)arg1 default:(_Bool)arg2;
- (id)initWithParams:(id)arg1;

@end

