//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "U8Plugin.h"

#import "SDKPassportDelegate.h"
#import "U8BaseExtMethods.h"
#import "U8Pay.h"
#import "U8User.h"

@class NSString;

@interface U8SDK_XD : U8Plugin <U8User, U8Pay, U8BaseExtMethods, SDKPassportDelegate>
{
    NSString *currentOrderId;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)dicWithJsonStr:(id)arg1;
- (void)txwyPassportUpdated;
- (void)txwyPayCancelled;
- (void)txwyDidPay:(id)arg1;
- (void)txwyDidPassport;
- (const char *)getData:(int)arg1 withParams:(id)arg2;
- (void)setData:(int)arg1 withParams:(id)arg2;
- (void)pay:(id)arg1;
- (_Bool)isNativePlugin;
- (void)submitGameData:(id)arg1;
- (void)showAccountCenter;
- (_Bool)hasAccountCenter;
- (void)switchAccount;
- (void)logout;
- (void)login;
- (void)didReceiveRemoteNotification:(id)arg1;
- (void)didReceiveLocalNotification:(id)arg1;
- (void)didFailToRegisterForRemoteNotificationsWithError:(id)arg1;
- (void)didRegisterForRemoteNotificationsWithDeviceToken:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)setupWithParams:(id)arg1;
- (id)initWithParams:(id)arg1;

@end

