//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNotification, UIView, UIViewController;

@protocol U8SDKDelegate <NSObject>
- (UIViewController *)GetViewController;
- (UIView *)GetView;

@optional
- (void)OnSDKError:(NSNotification *)arg1;
- (void)OnSwitchAccount:(NSNotification *)arg1;
- (void)OnEventCustom:(NSNotification *)arg1;
- (void)OnPayFailed:(NSNotification *)arg1;
- (void)OnPayPaid:(NSNotification *)arg1;
- (void)OnUserLogout:(NSNotification *)arg1;
- (void)OnUserLoginFailed:(NSNotification *)arg1;
- (void)OnUserLogin:(NSNotification *)arg1;
- (void)OnPlatformInitFailed:(NSNotification *)arg1;
- (void)OnPlatformInit:(NSNotification *)arg1;
@end

