//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface U8UserExtraData : NSObject
{
    int _dataType;
    int _serverID;
    int _moneyNum;
    NSString *_roleID;
    NSString *_roleName;
    NSString *_roleLevel;
    NSString *_serverName;
}

+ (id)dataFromJsonString:(id)arg1;
@property int moneyNum; // @synthesize moneyNum=_moneyNum;
@property(retain, nonatomic) NSString *serverName; // @synthesize serverName=_serverName;
@property int serverID; // @synthesize serverID=_serverID;
@property(retain, nonatomic) NSString *roleLevel; // @synthesize roleLevel=_roleLevel;
@property(retain, nonatomic) NSString *roleName; // @synthesize roleName=_roleName;
@property(retain, nonatomic) NSString *roleID; // @synthesize roleID=_roleID;
@property int dataType; // @synthesize dataType=_dataType;
- (void).cxx_destruct;
- (id)toJsonString;
- (id)initWithDict:(id)arg1;

@end

