//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol U8User
- (_Bool)isNativePlugin;
- (_Bool)hasAccountCenter;
- (void)switchAccount;
- (void)logout;
- (void)login;

@optional
- (NSString *)getUpdateAddress;
- (_Bool)isSupportLogin;
- (_Bool)isSupportLogout;
- (_Bool)isSupportExit;
- (_Bool)exit;
- (void)submitGameData:(NSString *)arg1;
- (void)showAccountCenter;
- (void)loginCustom:(NSString *)arg1;
@end

