//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIToolbar.h"

@class UIBarButtonItem;

@interface UniWebViewToolBar : UIToolbar
{
    UIBarButtonItem *_btnNext;
    UIBarButtonItem *_btnBack;
    UIBarButtonItem *_btnReload;
    UIBarButtonItem *_btnDone;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIBarButtonItem *btnDone; // @synthesize btnDone=_btnDone;
@property(retain, nonatomic) UIBarButtonItem *btnReload; // @synthesize btnReload=_btnReload;
@property(retain, nonatomic) UIBarButtonItem *btnBack; // @synthesize btnBack=_btnBack;
@property(retain, nonatomic) UIBarButtonItem *btnNext; // @synthesize btnNext=_btnNext;

@end

