//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKWebView.h"

@class NSMutableArray, NSMutableDictionary, NSString, UniWebSpinner, UniWebViewToolBar;

@interface UniWebView : WKWebView
{
    _Bool _showSpinnerWhenLoading;
    _Bool _viewAnimating;
    _Bool _openLinkInExternalBrowser;
    UniWebViewToolBar *_toolBar;
    UniWebSpinner *_spinner;
    NSString *_currentUrl;
    NSString *_currentUserAgent;
    NSMutableArray *_schemes;
    NSMutableDictionary *_headers;
    struct UIEdgeInsets _insets;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool openLinkInExternalBrowser; // @synthesize openLinkInExternalBrowser=_openLinkInExternalBrowser;
@property(nonatomic) _Bool viewAnimating; // @synthesize viewAnimating=_viewAnimating;
@property(retain, nonatomic) NSMutableDictionary *headers; // @synthesize headers=_headers;
@property(retain, nonatomic) NSMutableArray *schemes; // @synthesize schemes=_schemes;
@property(copy, nonatomic) NSString *currentUserAgent; // @synthesize currentUserAgent=_currentUserAgent;
@property(copy, nonatomic) NSString *currentUrl; // @synthesize currentUrl=_currentUrl;
@property(nonatomic) _Bool showSpinnerWhenLoading; // @synthesize showSpinnerWhenLoading=_showSpinnerWhenLoading;
@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
@property(retain, nonatomic) UniWebSpinner *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UniWebViewToolBar *toolBar; // @synthesize toolBar=_toolBar;
- (void)changeToInsets:(struct UIEdgeInsets)arg1 targetOrientation:(int)arg2;
- (void)updateToolBtn;
- (void)btnReloadPressed:(id)arg1;
- (void)btnDonePressed:(id)arg1;
- (void)setBounces:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

