//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WKNavigationDelegate.h"

@class NSMutableDictionary, NSString;

@interface UniWebViewManager : NSObject <WKNavigationDelegate>
{
    NSMutableDictionary *_webViewDic;
    int _orientationBeforeFullScreen;
    _Bool _multipleOrientation;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)webViewName:(id)arg1 setHorizontalScrollBarShow:(_Bool)arg2;
- (void)webViewName:(id)arg1 setVerticalScrollBarShow:(_Bool)arg2;
- (void)webViewName:(id)arg1 setValue:(id)arg2 forHeaderField:(id)arg3;
- (void)webViewName:(id)arg1 setAlpha:(float)arg2;
- (float)webViewNameGetAlpha:(id)arg1;
- (void)webViewSetUserAgent:(id)arg1;
- (id)webViewGetUserAgent:(id)arg1;
- (void)videoExitFullScreen:(id)arg1;
- (void)videoEnterFullScreen:(id)arg1;
- (id)webViewNameGetCurrentUrl:(id)arg1;
- (void)webViewDone:(id)arg1;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webViewName:(id)arg1 removeUrlScheme:(id)arg2;
- (void)webViewName:(id)arg1 addUrlScheme:(id)arg2;
- (id)webViewName:(id)arg1;
- (void)webViewName:(id)arg1 setSpinnerText:(id)arg2;
- (void)webViewName:(id)arg1 setSpinnerShowWhenLoading:(_Bool)arg2;
- (void)performJavaScript:(id)arg1;
- (void)webViewName:(id)arg1 evaluatingJavaScript:(id)arg2 shouldCallBack:(_Bool)arg3;
- (void)webViewName:(id)arg1 loadHTMLString:(id)arg2 baseURLString:(id)arg3;
- (void)webViewName:(id)arg1 setBounces:(_Bool)arg2;
- (void)webViewName:(id)arg1 setZoomEnable:(_Bool)arg2;
- (void)goForwardWebViewName:(id)arg1;
- (void)goBackWebViewName:(id)arg1;
- (_Bool)canGoForwardWebViewName:(id)arg1;
- (_Bool)canGoBackWebViewName:(id)arg1;
- (void)webViewName:(id)arg1 hideToolBarAnimate:(_Bool)arg2;
- (void)webViewName:(id)arg1 showToolBarAnimate:(_Bool)arg2;
- (void)setWebViewBackgroundColorName:(id)arg1 color:(id)arg2;
- (void)updateBackgroundWebViewName:(id)arg1 transparent:(_Bool)arg2;
- (void)removeWebViewName:(id)arg1;
- (void)webViewName:(id)arg1 show:(_Bool)arg2 fade:(_Bool)arg3 direction:(long long)arg4 duration:(float)arg5;
- (void)webViewNameCleanCookie:(id)arg1 forKey:(id)arg2;
- (void)webViewNameCleanCache:(id)arg1;
- (void)webViewNameStop:(id)arg1;
- (void)webViewNameReload:(id)arg1;
- (void)webviewName:(id)arg1 beginLoadURL:(id)arg2;
- (void)changeWebView:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (void)changeWebViewName:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (void)addManagedWebViewName:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (void)addManagedWebView:(id)arg1 forName:(id)arg2;
- (void)checkOrientationSupport;
- (id)webViewWithName:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

