//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YCNetTraceRoute : NSObject
{
    int port;
    int maxTTL;
    int readTimeout;
    id <YCNetTraceRouteDelegate> _delegate;
}

@property(nonatomic) __weak id <YCNetTraceRouteDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (unsigned char)doTraceRoute:(id)arg1;
- (id)init;

@end

